api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity' # default configuration for annotations
      - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
  allow_plain_identifiers: true
  graphql:
    graphiql:
      enabled: true
    graphql_playground:
      enabled: true
  show_webby: false
  enable_swagger: true
  eager_loading:
    enabled: false
    force_eager: false
    max_joins: 100
    fetch_partial: true
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    versions: [ 3 ]